"""Dataset report: what the splits actually contain, and how far apart they are.

Emitted as a DVC metric so it lives in git rather than MinIO. Two consequences worth
the effort: `git diff` on the report shows how a change to the split policy changed the
dataset, and `dvc metrics diff` compares across commits without anyone re-running an
analysis by hand.

This is also the first half of the drift monitor. Measuring input drift means comparing
a live stream's distribution against the training distribution -- and this computes the
training distribution. P4 adds the comparison, not the statistics.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path


def split_stats(coco: dict, provenance: dict) -> dict:
    id_to_name = {c["id"]: c["name"] for c in coco["categories"]}
    n_images, n_boxes = len(coco["images"]), len(coco["annotations"])

    class_counts = Counter(id_to_name[a["category_id"]] for a in coco["annotations"])
    per_image = Counter(a["image_id"] for a in coco["annotations"])

    locations = Counter()
    hours = Counter()
    for image in coco["images"]:
        prov = provenance.get(str(image["id"]))
        if not prov:
            continue
        locations[prov["location"]] += 1
        if prov.get("local_hour") is not None:
            hours[prov["local_hour"]] += 1

    # Box area relative to image area -- a scale proxy. Small-object performance is
    # where input resolution shows up, so this is the number to watch if the image
    # size is ever changed.
    areas = defaultdict(int)
    sizes = {im["id"]: im["width"] * im["height"] for im in coco["images"]}
    for a in coco["annotations"]:
        frac = a["area"] / sizes[a["image_id"]]
        if frac < 0.001:
            bucket = "tiny"
        elif frac < 0.01:
            bucket = "small"
        elif frac < 0.1:
            bucket = "medium"
        else:
            bucket = "large"
        areas[bucket] += 1

    return {
        "n_images": n_images,
        "n_boxes": n_boxes,
        "boxes_per_image": round(n_boxes / n_images, 2) if n_images else 0.0,
        "images_without_boxes": n_images - len(per_image),
        "class_share_pct": {
            k: round(v / n_boxes * 100, 2) for k, v in sorted(class_counts.items())
        },
        "class_counts": dict(sorted(class_counts.items())),
        "location_images": dict(sorted(locations.items())),
        "capture_hour_images": {str(h): hours[h] for h in sorted(hours)},
        "box_scale_pct": {
            k: round(areas[k] / n_boxes * 100, 2)
            for k in ("tiny", "small", "medium", "large")
            if areas.get(k)
        },
    }


def shift(train: dict, test: dict) -> dict:
    """Percentage-point movement in class share, train -> test.

    Reported as a signed delta and as total variation distance, which summarises the
    whole distribution in one number and is what the drift monitor will threshold on.
    """
    classes = sorted(set(train["class_share_pct"]) | set(test["class_share_pct"]))
    deltas = {
        c: round(test["class_share_pct"].get(c, 0.0) - train["class_share_pct"].get(c, 0.0), 2)
        for c in classes
    }
    tvd = round(sum(abs(d) for d in deltas.values()) / 2, 2)
    return {"class_share_delta_pp": deltas, "total_variation_pct": tvd}


def render_markdown(report: dict) -> str:
    splits = report["splits"]
    names = [n for n in ("train", "val", "test") if n in splits]
    lines = ["# Dataset report", "", "Generated by the `report` pipeline stage.", ""]

    lines += ["| split | images | boxes | boxes/image | locations |", "|---|--:|--:|--:|---|"]
    for n in names:
        s = splits[n]
        locs = ", ".join(s["location_images"])
        lines.append(
            f"| {n} | {s['n_images']:,} | {s['n_boxes']:,} | {s['boxes_per_image']} | {locs} |"
        )

    lines += [
        "",
        "## Class share (%)",
        "",
        "| class | " + " | ".join(names) + " | train→test |",
        "|---|" + "--:|" * (len(names) + 1),
    ]
    classes = sorted({c for n in names for c in splits[n]["class_share_pct"]})
    deltas = report.get("shift", {}).get("class_share_delta_pp", {})
    for c in classes:
        row = " | ".join(f"{splits[n]['class_share_pct'].get(c, 0.0):.1f}" for n in names)
        d = deltas.get(c)
        lines.append(f"| {c} | {row} | {d:+.1f} pp |" if d is not None else f"| {c} | {row} | |")

    if "shift" in report:
        tv = report["shift"]["total_variation_pct"]
        lines += [
            "",
            f"**Total variation train→test: {tv:.1f}%**",
            "",
            "That figure is the drift baseline: a live stream measured against the training",
            "distribution has to be read relative to how far the held-out location already",
            "sits from it.",
        ]

    lines += [
        "",
        "## Box scale (% of boxes, area relative to image)",
        "",
        "| split | " + " | ".join(("tiny <0.1%", "small <1%", "medium <10%", "large")) + " |",
        "|---|--:|--:|--:|--:|",
    ]
    for n in names:
        b = splits[n]["box_scale_pct"]
        lines.append(
            f"| {n} | "
            + " | ".join(f"{b.get(k, 0.0):.1f}" for k in ("tiny", "small", "medium", "large"))
            + " |"
        )

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--splits-dir", type=Path, required=True)
    ap.add_argument("--provenance", type=Path, required=True)
    ap.add_argument("--out-json", type=Path, required=True)
    ap.add_argument("--out-md", type=Path, required=True)
    args = ap.parse_args()

    provenance = json.loads(args.provenance.read_text())
    report: dict = {"splits": {}}
    for name in ("train", "val", "test"):
        path = args.splits_dir / f"{name}.json"
        if path.exists():
            report["splits"][name] = split_stats(json.loads(path.read_text()), provenance)

    if "train" in report["splits"] and "test" in report["splits"]:
        report["shift"] = shift(report["splits"]["train"], report["splits"]["test"])

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    args.out_md.write_text(render_markdown(report))

    for name, s in report["splits"].items():
        print(
            f"{name:<6} {s['n_images']:>7,} images {s['n_boxes']:>8,} boxes "
            f"{s['boxes_per_image']:>6}/img"
        )
    if "shift" in report:
        print(f"\ntotal variation train->test: {report['shift']['total_variation_pct']}%")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
